# Generated by Django 2.0 on 2019-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last_name')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('dificulty', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcersiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='user_id')),
                ('reps', models.CharField(blank=True, max_length=30, null=True, verbose_name='reps')),
                ('steps', models.CharField(blank=True, max_length=30, null=True, verbose_name='steps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcersiceDataDificultyWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(blank=True, max_length=100, null=True, verbose_name='difficulty')),
                ('excercise', models.CharField(blank=True, max_length=100, null=True, verbose_name='excercise')),
                ('reps', models.CharField(blank=True, max_length=100, null=True, verbose_name='reps')),
                ('steps', models.CharField(blank=True, max_length=100, null=True, verbose_name='steps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
